Fifth_project/Fifth_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from base_app import views
urlpatterns = [

    url(r'^$',views.index, name ='index'),
    url('admin/', admin.site.urls),
    url(r'^base_app/',include('base_app.urls')),
    url(r'^logout/$', views.user_logout, name = "logout")
]

Fifth_project/base_app/urls.py
from django.conf.urls import url
from base_app import views

# SET THE NAMESPACE!
app_name = 'base_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[


    url(r'^user_login/$',views.user_login,name='user_login' ),
    url(r'^register/$',views.register,name='register'),
]

Fifth_project/base_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import URLField

# Create your models here.

class UserProfileInfo(models.Model):
      # Create relationship (don't inherit from User!)
       user = models.OneToOneField(User,on_delete=models.CASCADE)

           # Add any additional attributes you want

       portfolio_site = models.URLField(blank = True)    
       # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”

       profile_pic = models.ImageField(upload_to='profile_pics',blank= True)


       def __str__(self):

           return self.user.username

Fifth_project/base_app/forms.py
from django import forms
from django.contrib.auth.models import User
from base_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic') 





    

Fifth_project/base_app/views.py
from django.shortcuts import render
from base_app.forms import UserForm,UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

def index(request):
    return render(request,"base_app/index.html")

@login_required
def user_logout(request):
     logout(request)
     return HttpResponseRedirect(reverse('index'))

\

\

def register(request):
     registered = False
     if request.method == "POST" :
         user_form = UserForm(data = request.POST)
         profile_form = UserProfileInfoForm(data = request.POST)
         if user_form.is_valid() and profile_form.is_valid():

             user = user_form.save()

             user.set_password(user.password)

             user.save()

             profile =  profile_form.save(commit=False)
             profile.user = user #need to understand #

             if 'profile_pic' in request.FILES :
                 print('found it')
                 profile.profile_pic = request.FILES['profile_pic']# need to understand

                 profile.save()

             registered = True
         else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)
        
     else:
         user_form = UserForm()
         profile_form = UserProfileInfoForm()            
     return render(request,'base_app/register.html',{'user_form':user_form, 'profile_form':profile_form,'registered':registered})



def user_login(request):

    if request.method == 'POST':
         # First get the username and password supplied
       
       username = request.POST.get('username')
       password = request.POST.get('password')

          # Django's built-in authentication function:

       user = authenticate(username=username,password =password)
             # If we have a user

       if user:
           if user.is_active: # need to understand
                # Log the user in.
              login(request,user) 
              # Send the user back to some page.
                # In this case their homepage.   
              return HttpResponseRedirect(reverse('index')) 
           else :
               return HttpResponse('user is not active')
       else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
          


    else:
        #Nothing has been provided for username or password.
       return render(request,'base_app/login.html', {})
 





# Create your views here.

Fifth_project/templates/base_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    
</head>
<body>
   
      
        
         <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
         <div class=" container">   
         <ul class = "nav navbar-nav">   
         <li><a class = "navbar-brand" href="{% url 'index'%}">brand</a></li>
         <li><a class = "nav-link" href="{% url 'admin:index'%}">Admin</a></li>
         <li><a class ="nav-link" href="{% url 'base_app:register'%}" >register</a></li>

         {# Some logic on what to display for last item#}
         {% if user.is_authenticated %}
         <li><a class ="nav-link"  href="{% url 'logout' %}">Logout</a></li>
         {% else %}
          <li><a  class ="nav-link" href="{% url 'base_app:user_login' %}">Login</a>
          </li>
          {% endif %}
       
     </ul>
  
         
    </div>
</nav>

<div class ='container'>
 
    {% block body_block %}
    {% endblock %}


</div>

    
</body>
</html>

Fifth_project/templates/base_app/index.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
    {% block body_block%}

    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page</h1>

    {% endblock %}




  


  

Fifth_project/templates/base_app/login.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}

{% load staticfiles % }

{% block body_block %}
<div class = "jumbotron">
    <h1>please Login</h1>
  <form action="{% url 'base_app:user_login' %}" method="POST" >
      {% csrf_token %}
      <label for="username">Username</label>
       <input type="text" name="username" placeholder="Enter username">


       <label for="password">password</label>
       <input type="password" name="password">

       <input type="submit" name ="" value ="Login"> 
     

  </form>


 </div>   
</div>


{% endblock %}

Fifth_project/templates/base_app/register.html
<!DOCTYPE html>
{% extends "base_app/base.html" %}
{% load staticfiles %}


{% block body_block %}

<div class="container">
<div class="jumbotron">
  
    {% if registered %}
      
     <h1>thanku for registering</h1>

    {% else %}
      <h1>Register Here</h1>
      <h3>Just fill out the form.</h3>

      <form method="POST" enctype="multipart/form-data" >
              {%csrf_token%}
              {{user_form.as_p}}
              {{profile_form.as_p}}
              <input type="submit" name="submit" value="Register">
      </form>        
    {% endif %}   

</div>


</div>

{% endblock %}